# Generated by Django 4.2.2 on 2023-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YokoCino', '0002_alter_blog_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blogimg'),
        ),
    ]
